# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b41d2deaf54d736f0444d92972d5247eb39441491347cff1d5916b8368e4d6775e80c3c20778bc4955434be94280da4efedca597cc3de1c8f6f227aea5c7fac9

test:
  secret_key_base: fcb4b38e2babefa1fd1a9bcd38d385234acc05ad9d62a7c8ed1d12668ce12e37e208f9d3b929b2721fabf2b33a8870b0933c6693ba4bd5d9ad0c370e3f361f2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
